// <auto-generated />
using System;
using CoreMs.CommunicationMs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreMs.CommunicationMs.Infrastructure.Migrations
{
    [DbContext(typeof(CommunicationMsDbContext))]
    partial class CommunicationMsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communication_ms")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.EmailAttachmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Checksum")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("document_uuid");

                    b.Property<long>("EmailMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("email_message_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .HasDatabaseName("idx_email_attachment_email");

                    b.ToTable("email_attachment", "communication_ms");
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SentById")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by_id");

                    b.Property<string>("SentByType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sent_by_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("character varying(31)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_message_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_message_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_message_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_message_user");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("message", "communication_ms");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.EmailMessageEntity", b =>
                {
                    b.HasBaseType("CoreMs.CommunicationMs.Core.Entities.MessageEntity");

                    b.Property<string>("Bcc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bcc");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Cc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cc");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_type");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender");

                    b.Property<string>("SenderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sender_name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.ToTable("email", "communication_ms");
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.SmsMessageEntity", b =>
                {
                    b.HasBaseType("CoreMs.CommunicationMs.Core.Entities.MessageEntity");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Sid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sid");

                    b.ToTable("sms", "communication_ms");
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.EmailAttachmentEntity", b =>
                {
                    b.HasOne("CoreMs.CommunicationMs.Core.Entities.EmailMessageEntity", "EmailMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.EmailMessageEntity", b =>
                {
                    b.HasOne("CoreMs.CommunicationMs.Core.Entities.MessageEntity", null)
                        .WithOne()
                        .HasForeignKey("CoreMs.CommunicationMs.Core.Entities.EmailMessageEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.SmsMessageEntity", b =>
                {
                    b.HasOne("CoreMs.CommunicationMs.Core.Entities.MessageEntity", null)
                        .WithOne()
                        .HasForeignKey("CoreMs.CommunicationMs.Core.Entities.SmsMessageEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoreMs.CommunicationMs.Core.Entities.EmailMessageEntity", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
