<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CoreMs.TemplateMs.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionRoot)template-ms\src\CoreMs.TemplateMs.Api\CoreMs.TemplateMs.Api.csproj" />
    <ProjectReference Include="$(SolutionRoot)template-ms\src\CoreMs.TemplateMs.Core\CoreMs.TemplateMs.Core.csproj" />
    <ProjectReference Include="$(SolutionRoot)template-ms\src\CoreMs.TemplateMs.Infrastructure\CoreMs.TemplateMs.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsCheck.Xunit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
